### ISSUE TITLE
Figure out primary repo that will be used

### ISSUE THREAD

**Issue by natalysheinin** [torontocatrescue/CentralManagementSystem#4]

**Comment by anirudhmungre** [comment]
I think we should create a completely fresh repo and start merging things in there. The reason for that is we still don't know what aspects of each project we are incorporating. This requirement will most likely be met in a user requirement analysis session.

**Comment by natalysheinin** [comment]
@anirudhmungre Cool. Let's use https://github.com/torontocatrescue/CentralManagementSystem
